services:
  - type: web
    name: tesis-videovigilancia-backend
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MODELS_DIR
        value: models_mix2
      - key: POSE_WEIGHTS
        value: yolo11s-pose.pt
      - key: FUSION_W
        value: "0.50"
      - key: CORS_ORIGINS
        value: "*"
      - key: BOSS_CODE
        sync: false
